### ISSUE TITLE
5.5.18 on Yosemite

### ISSUE THREAD

**Issue by gazley** [majksner/php-phalcon-mamp#15]
Hi,

I've just upgraded you Yosemite after previously compiling my own Phalcon on Mountain Lion.

I've tried your phalcon.so but it doesn't seem to work on Yosemite. Can you confirm this to be the case?

Many thanks,

--Gary

**Comment by jasontrask** [comment]
Just noticed this issue when installed, and thought I'd mention that I've successfully added the 5.5.18 compiled version of phalcon.so. I'm also running 10.10.1 with MAMP 3.0.7.3. Apache restarted without any issue.

PS. Thanks majksner - this was really useful!

**Comment by DaqiHong** [comment]
gazley, I also got the same error.

**Comment by majksner** [comment]
I need more insight I can't reproduce it on my end.

**Comment by brainformatik** [comment]
just tested with yosemite 10.10.2 and mamp 3.0.7.3 and php 5.5.18 -> its rocks!

majksner, any plans to compile and distribute phalcon 2 beta for mamp?

**Comment by vhanla** [comment]
I followed your setup instructions to use with PHP 5.5.18 on MAMP, but it failed with the following errors:

    [Tue Feb 24 01:45:15 2015] [notice] Digest: generating secret for digest authentication ...
    [Tue Feb 24 01:45:15 2015] [notice] Digest: done
    [Tue Feb 24 01:45:15 2015] [notice] Apache/2.2.29 (Unix) mod_fastcgi/2.4.6 mod_wsgi/3.4     Python/2.7.8 PHP/5.5.18 mod_ssl/2.2.29 OpenSSL/0.9.8zc DAV/2 mod_perl/2.0.8 Perl/v5.20.0 configured -- resuming normal operations
    [Tue Feb 24 01:45:19 2015] [notice] caught SIGTERM, shutting down
    [Tue Feb 24 01:46:32 2015] [notice] FastCGI: process manager initialized (pid 9624)
    [Tue Feb 24 01:48:55 2015] [notice] FastCGI: process manager initialized (pid 10363)

I tried it with "PHP with CGI host" mode. Apache now works, but now each page shows error 500. I disable Phalcon extension and everything works normal again, without Error 500.
BTW:  I tried modifying .htaccess file as well as httpd.conf, but it doesn't work. 

I'm using Yosemite 10.10.2 and MAMP 3.0.7.3 with PHP 5.5.18
