### ISSUE TITLE
Update to MAMP 3.3?

### ISSUE THREAD

**Issue by ignaciovazquez** [majksner/php-phalcon-mamp#18]
Hi,

Any chance we can get MAMP 3.3 (with PHP 5.6.9) support?

Thanks!

**Comment by iamphilrae** [comment]
Hi,
I've just added a Pull request with this for MAMP 3.3 and PHP 5.6.10. If you update your MAMP, it should pull in the new PHP version (I just installed it this morning). Hope it works.

Phil

**Comment by majksner** [comment]
@iamphilrae Added support for MAMP 3.3, It's merged.
