### ISSUE TITLE
PHP 7.0

### ISSUE THREAD

**Issue by geoidesic** [majksner/php-phalcon-mamp#22]
Any chance of getting this working with PHP 7.0?
Phalcon supports 7.0

**Comment by majksner** [comment]
I don't see any news about PHP 7.0 support on their Github repo.

**Comment by geoidesic** [comment]
My bad, you're right.

**Comment by mynumbercrunching** [comment]
any chance at a MAMP .so for PHP 7?

i have not figured out how to do it,  you good work spoiled me.  LOL

cheers.


> On Jan 15, 2016, at 7:08 PM, Nikola Majksner <notifications@github.com> wrote:
> 
> I don't see any news about PHP 7.0 support on their Github repo.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/majksner/php-phalcon-mamp/issues/22#issuecomment-171945110>.
> 


thomas wm. benson | student of humanity & citizen of the world  | diogenes@me.com  |  +1. 239 . 206 . 3240  

"The truth is not for all men, but only for those who seek it."  Any Rand
