### ISSUE TITLE
Apache is not coming up

### ISSUE THREAD

**Issue by kadnan** [majksner/php-phalcon-mamp#27]
I am using php5.6.10 version. I added the so file in `php.ini` file but Apache is not coming up. How do I trace?

**Comment by diego-vieira** [comment]
Start by looking at apache logs. If you still can't find the issue, try contacting MAMP support team.

![screen shot 2016-06-19 at 12 23 00](https://cloud.githubusercontent.com/assets/930792/16178229/bc157014-3618-11e6-91bc-3a48284c7652.jpg)
