### ISSUE TITLE
Trouble with 7.0.10 

### ISSUE THREAD

**Issue by anhkha1205** [majksner/php-phalcon-mamp#31]
I installed Mamp 4.0.2 on my iMac (el Capitan).
Download phalcon.so inside php 7.0.10 folder and went to Applications/MAMP/bin/php/php7.0.10/lib/php/extensions/no-debug-non-zts-20151012 and paste the phalcon.so there and then add extension=phalcon.so to /Applications/MAMP/bin/php/php7.0.10/conf/php.ini (which is the loaded configuration file) but once I restart MAMP Apache doesn't run.

**Comment by anhkha1205** [comment]
but if i take out the extension=phalcon.so, apache in MAMP runs fine again. phalcon.so doesn't show up as an executable file, not sure if that means much.

**Comment by loudcode** [comment]
having same issue as anhkha1205.
Running MAMP 4.0.5 on OSX 10.11.4. 
Seems that MAMP 4 does not write a PHP error log, so no help there.
Any ideas ?

**Comment by majksner** [comment]
Please check updated version for PHP 7.0.12 and MAMP 4.0.6. Let me know if any problems.

**Comment by snelledre** [comment]
I have also the same problems when I insert extension=phalcon.so then apache doesn't run.
Without the insert extension=phalcon.so apache runs fine.
I have php 7.0.12 with MAMP 4.0.6 thats meaning the issue is stil actual.

**Comment by SonnyLCD** [comment]
Just tried with MAMP 4.0.6 and PHP 7.0.12 ... same problem, seems that Apache does not consider the phalcon.so file as executable, so it chokes on startup...

**Comment by majksner** [comment]
Can you try changing chmod?

`
chmod +x filename.so
`

**Comment by SonnyLCD** [comment]
Hi Majksner
Thanks for super fast response!

I tried chmod, but still same. Apache doesn't start.

**Comment by nurtext** [comment]
Mostly missing PHP source/header files. Try downloading the php sources for your version and place it into: `/Applications/MAMP/bin/php/phpx.x.x/include/php`

**Comment by malcocerGit** [comment]
Hi, I have the same problem but I worked with MAMP 5.3 | PHP 5.6.10.

I tried to add the files as @nurtext say's but nothing works, also I have this 

> Fatal error: Class 'Phalcon\Loader' not found in /Users/imagenweb/Documents/GIT/framework2017/framework2.0/index.php on line 18
