### ISSUE TITLE
Update to phalcon 4.x

### ISSUE THREAD

**Issue by casparjones** [majksner/php-phalcon-mamp#36]
Will the latest version of Phalcon 4.0 (https://blog.phalcon.io/post/phalcon-4-0-0-released) also be available in your great collection?
On Mac it is very difficult to compile phalcon and then use it with mamp pro, so it would be very helpful if the binaries could be provided here.

**Comment by majksner** [comment]
You should be able to easily compile Phalcon with:

```shell
pecl install phalcon
```

https://documentation.mamp.info/en/MAMP-PRO-Mac/How-Tos/General/PECL/

**Comment by casparjones** [comment]
Unfortunately I always get errors when building the extension, so I find the repository here very helpful. Can you give a hint to the error:
In file included from /private/tmp/pear/temp/psr/php_psr.c:6:
In file included from /Applications/MAMP/bin/php/php7.3.8/include/php/main/php.h:33:
In file included from /Applications/MAMP/bin/php/php7.3.8/include/php/Zend/zend.h:27:
In file included from /Applications/MAMP/bin/php/php7.3.8/include/php/Zend/zend_types.h:25:
/Applications/MAMP/bin/php/php7.3.8/include/php/Zend/zend_portability.h:43:11: fatal error: 'zend_config.h' file not found
# include <zend_config.h>
          ^~~~~~~~~~~~~~~
1 error generated.
make: *** [php_psr.lo] Error 1
ERROR: `make' failed

**Comment by majksner** [comment]
Download [PHP 7.3.8 source](https://www.php.net/distributions/php-7.3.8.tar.bz2 ) and extract achive in `/Applications/MAMP/bin/php/php7.3.8/include/`

`include` folder should look like this:

```
.
├── CODING_STANDARDS
├── CONTRIBUTING.md
├── CREDITS
├── EXTENSIONS
├── INSTALL
├── LICENSE
├── Makefile.frag
├── Makefile.gcov
├── Makefile.global
├── NEWS
├── README.EXT_SKEL
├── README.GIT-RULES
├── README.MAILINGLIST_RULES
├── README.NEW-OUTPUT-API
├── README.PARAMETER_PARSING_API
├── README.REDIST.BINS
├── README.RELEASE_PROCESS
├── README.SELF-CONTAINED-EXTENSIONS
├── README.STREAMS
├── README.SUBMITTING_PATCH
├── README.TESTING
├── README.UNIX-BUILD-SYSTEM
├── README.WIN32-BUILD-SYSTEM
├── README.input_filter
├── README.md
├── TSRM
├── UPGRADING
├── UPGRADING.INTERNALS
├── Zend
├── acinclude.m4
├── aclocal.m4
├── appveyor
├── build
├── buildconf
├── buildconf.bat
├── config.guess
├── config.sub
├── configure
├── configure.ac
├── ext
├── footer
├── generated_lists
├── genfiles
├── header
├── install-sh
├── ltmain.sh
├── main
├── makedist
├── missing
├── mkinstalldirs
├── pear
├── php.gif
├── php.ini-development
├── php.ini-production
├── php7.spec.in
├── run-tests.php
├── sapi
├── scripts
├── server-tests-config.php
├── server-tests.php
├── snapshot
├── stamp-h.in
├── tests
├── travis
├── vcsclean
└── win32
```

Then run `pecl install phalcon`
